### ISSUE TITLE
[Feature Request] Exception flag

### ISSUE THREAD

**Issue by CBroz1** [hukkinj1/mdformat-black#6]
I put together a markdown file that demonstrates the kinds of changes that `black` makes with before/after blocks. Is there a comment I can apply to the 'before' block to tell `mdformat-black` to ignore it?

for example...
````Markdown
Pre-black block
<!-- mdformat-black ignore -->
```python
a = 'a'
```
````

**Comment by hukkin** [comment]
Hey!

Would it work if you used Black's `fmt: off` feature https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#ignoring-sections

````md
Pre-black block
```python
# fmt: off
dont = 'format this'
# fmt: on
```
````

**Comment by CBroz1** [comment]
`fmt: off` is not ideal, as it will be visible to folks looking at the markdown. My solution for this doc was to commit it with mdformat turned off, and then re-enable

**Comment by hukkin** [comment]
Thanks for explaining. I think https://github.com/executablebooks/mdformat/issues/53 should be the way to implement this. I don't think this should be special cased here. Closing.
